// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateIterations implements pgx.CopyFromSource.
type iteratorForCreateIterations struct {
	rows                 []CreateIterationsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateIterations) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateIterations) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].SessionID,
		r.rows[0].IterationNumber,
		r.rows[0].Title,
	}, nil
}

func (r iteratorForCreateIterations) Err() error {
	return nil
}

func (q *Queries) CreateIterations(ctx context.Context, arg []CreateIterationsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"session_iterations"}, []string{"id", "session_id", "iteration_number", "title"}, &iteratorForCreateIterations{rows: arg})
}

// iteratorForCreateQuestions implements pgx.CopyFromSource.
type iteratorForCreateQuestions struct {
	rows                 []CreateQuestionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateQuestions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateQuestions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].IterationID,
		r.rows[0].QuestionNumber,
		r.rows[0].Status,
		r.rows[0].Question,
		r.rows[0].Explanation,
	}, nil
}

func (r iteratorForCreateQuestions) Err() error {
	return nil
}

func (q *Queries) CreateQuestions(ctx context.Context, arg []CreateQuestionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"iteration_questions"}, []string{"id", "iteration_id", "question_number", "status", "question", "explanation"}, &iteratorForCreateQuestions{rows: arg})
}
