// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFile = `-- name: AddFile :one
INSERT INTO project_files (id, project_id, filename, size, content_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, filename, size, content_type, created_at
`

type AddFileParams struct {
	ID          pgtype.UUID `json:"id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	Filename    string      `json:"filename"`
	Size        int64       `json:"size"`
	ContentType string      `json:"content_type"`
}

func (q *Queries) AddFile(ctx context.Context, arg AddFileParams) (ProjectFile, error) {
	row := q.db.QueryRow(ctx, addFile,
		arg.ID,
		arg.ProjectID,
		arg.Filename,
		arg.Size,
		arg.ContentType,
	)
	var i ProjectFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.Size,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectFile = `-- name: DeleteProjectFile :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProjectFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectFile, id)
	return err
}

const getFiles = `-- name: GetFiles :many
SELECT id, project_id, filename, size, content_type, created_at
FROM project_files
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetFiles(ctx context.Context, projectID pgtype.UUID) ([]ProjectFile, error) {
	rows, err := q.db.Query(ctx, getFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectFile{}
	for rows.Next() {
		var i ProjectFile
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Filename,
			&i.Size,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
