// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IterationQuestion struct {
	ID             pgtype.UUID      `json:"id"`
	IterationID    pgtype.UUID      `json:"iteration_id"`
	QuestionNumber int32            `json:"question_number"`
	Status         string           `json:"status"`
	Question       string           `json:"question"`
	Explanation    string           `json:"explanation"`
	Answer         pgtype.Text      `json:"answer"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	AnsweredAt     pgtype.Timestamp `json:"answered_at"`
}

type Project struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type ProjectFile struct {
	ID          pgtype.UUID      `json:"id"`
	ProjectID   pgtype.UUID      `json:"project_id"`
	Filename    string           `json:"filename"`
	Size        int64            `json:"size"`
	ContentType string           `json:"content_type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID               pgtype.UUID      `json:"id"`
	ProjectID        pgtype.UUID      `json:"project_id"`
	Status           string           `json:"status"`
	Type             pgtype.Text      `json:"type"`
	UserGoal         pgtype.Text      `json:"user_goal"`
	ProjectContext   pgtype.Text      `json:"project_context"`
	CurrentIteration int32            `json:"current_iteration"`
	Result           pgtype.Text      `json:"result"`
	Error            pgtype.Text      `json:"error"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type SessionIteration struct {
	ID              pgtype.UUID      `json:"id"`
	SessionID       pgtype.UUID      `json:"session_id"`
	IterationNumber int32            `json:"iteration_number"`
	Title           string           `json:"title"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type SessionMessage struct {
	ID          pgtype.UUID      `json:"id"`
	SessionID   pgtype.UUID      `json:"session_id"`
	MessageText string           `json:"message_text"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type TelegramSession struct {
	UserID    int64            `json:"user_id"`
	SessionID pgtype.UUID      `json:"session_id"`
	StateData []byte           `json:"state_data"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type TelegramUser struct {
	UserID       int64            `json:"user_id"`
	Username     pgtype.Text      `json:"username"`
	FirstName    pgtype.Text      `json:"first_name"`
	LastName     pgtype.Text      `json:"last_name"`
	LanguageCode pgtype.Text      `json:"language_code"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	LastActiveAt pgtype.Timestamp `json:"last_active_at"`
}
