// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFile(ctx context.Context, arg AddFileParams) (ProjectFile, error)
	AquireSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	CreateFilledSession(ctx context.Context, arg CreateFilledSessionParams) (Session, error)
	CreateIteration(ctx context.Context, arg CreateIterationParams) (SessionIteration, error)
	CreateIterations(ctx context.Context, arg []CreateIterationsParams) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (IterationQuestion, error)
	CreateQuestions(ctx context.Context, arg []CreateQuestionsParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionMessage(ctx context.Context, arg CreateSessionMessageParams) (SessionMessage, error)
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteProjectFile(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionMessages(ctx context.Context, sessionID pgtype.UUID) error
	DeleteTelegramSession(ctx context.Context, userID int64) error
	GetCurrentIteration(ctx context.Context, sessionID pgtype.UUID) (SessionIteration, error)
	GetFiles(ctx context.Context, projectID pgtype.UUID) ([]ProjectFile, error)
	GetIterationByID(ctx context.Context, id pgtype.UUID) (SessionIteration, error)
	GetNextIteration(ctx context.Context, sessionID pgtype.UUID) (SessionIteration, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetQuestionByID(ctx context.Context, id pgtype.UUID) (IterationQuestion, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionMessages(ctx context.Context, sessionID pgtype.UUID) ([]SessionMessage, error)
	GetTelegramSession(ctx context.Context, userID int64) (TelegramSession, error)
	GetTelegramSessionBySessionID(ctx context.Context, sessionID pgtype.UUID) (TelegramSession, error)
	GetTelegramSessionWithSession(ctx context.Context, userID int64) (GetTelegramSessionWithSessionRow, error)
	GetUnansweredQuestions(ctx context.Context, sessionID pgtype.UUID) ([]IterationQuestion, error)
	ListIterationsBySession(ctx context.Context, sessionID pgtype.UUID) ([]SessionIteration, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListQuestionsByIteration(ctx context.Context, iterationID pgtype.UUID) ([]IterationQuestion, error)
	ListQuestionsBySession(ctx context.Context, sessionID pgtype.UUID) ([]IterationQuestion, error)
	ResetSessionIteration(ctx context.Context, id pgtype.UUID) (Session, error)
	SkipQustion(ctx context.Context, id pgtype.UUID) error
	UpdateQuestionAnswer(ctx context.Context, arg UpdateQuestionAnswerParams) error
	UpdateSessionIteration(ctx context.Context, id pgtype.UUID) (Session, error)
	UpdateSessionProjectContext(ctx context.Context, arg UpdateSessionProjectContextParams) (Session, error)
	UpdateSessionRAGProjectContext(ctx context.Context, arg UpdateSessionRAGProjectContextParams) (Session, error)
	UpdateSessionResult(ctx context.Context, arg UpdateSessionResultParams) (Session, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error)
	UpdateSessionType(ctx context.Context, arg UpdateSessionTypeParams) (Session, error)
	UpdateSessionUserGoal(ctx context.Context, arg UpdateSessionUserGoalParams) (Session, error)
	UpsertTelegramSession(ctx context.Context, arg UpsertTelegramSessionParams) error
}

var _ Querier = (*Queries)(nil)
