// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionMessage = `-- name: CreateSessionMessage :one
INSERT INTO session_messages (session_id, message_text, created_at)
VALUES ($1, $2, NOW())
RETURNING id, session_id, message_text, created_at
`

type CreateSessionMessageParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	MessageText string      `json:"message_text"`
}

func (q *Queries) CreateSessionMessage(ctx context.Context, arg CreateSessionMessageParams) (SessionMessage, error) {
	row := q.db.QueryRow(ctx, createSessionMessage, arg.SessionID, arg.MessageText)
	var i SessionMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageText,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM session_messages
WHERE session_id = $1
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionMessages, sessionID)
	return err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, message_text, created_at
FROM session_messages
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSessionMessages(ctx context.Context, sessionID pgtype.UUID) ([]SessionMessage, error) {
	rows, err := q.db.Query(ctx, getSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMessage{}
	for rows.Next() {
		var i SessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
