// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTelegramSession = `-- name: DeleteTelegramSession :exec
DELETE FROM telegram_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteTelegramSession(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteTelegramSession, userID)
	return err
}

const getTelegramSession = `-- name: GetTelegramSession :one
SELECT user_id, session_id, state_data, created_at, updated_at
FROM telegram_sessions
WHERE user_id = $1
`

func (q *Queries) GetTelegramSession(ctx context.Context, userID int64) (TelegramSession, error) {
	row := q.db.QueryRow(ctx, getTelegramSession, userID)
	var i TelegramSession
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.StateData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelegramSessionBySessionID = `-- name: GetTelegramSessionBySessionID :one
SELECT user_id, session_id, state_data, created_at, updated_at
FROM telegram_sessions
WHERE session_id = $1
`

func (q *Queries) GetTelegramSessionBySessionID(ctx context.Context, sessionID pgtype.UUID) (TelegramSession, error) {
	row := q.db.QueryRow(ctx, getTelegramSessionBySessionID, sessionID)
	var i TelegramSession
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.StateData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelegramSessionWithSession = `-- name: GetTelegramSessionWithSession :one
SELECT
    ts.user_id,
    ts.session_id,
    ts.state_data,
    ts.created_at as tg_created_at,
    ts.updated_at as tg_updated_at,
    s.id as session_id_full,
    s.status as session_status,
    s.type as session_type,
    s.project_id as session_project_id
FROM telegram_sessions ts
LEFT JOIN sessions s ON ts.session_id = s.id
WHERE ts.user_id = $1
`

type GetTelegramSessionWithSessionRow struct {
	UserID           int64            `json:"user_id"`
	SessionID        pgtype.UUID      `json:"session_id"`
	StateData        []byte           `json:"state_data"`
	TgCreatedAt      pgtype.Timestamp `json:"tg_created_at"`
	TgUpdatedAt      pgtype.Timestamp `json:"tg_updated_at"`
	SessionIDFull    pgtype.UUID      `json:"session_id_full"`
	SessionStatus    pgtype.Text      `json:"session_status"`
	SessionType      pgtype.Text      `json:"session_type"`
	SessionProjectID pgtype.UUID      `json:"session_project_id"`
}

func (q *Queries) GetTelegramSessionWithSession(ctx context.Context, userID int64) (GetTelegramSessionWithSessionRow, error) {
	row := q.db.QueryRow(ctx, getTelegramSessionWithSession, userID)
	var i GetTelegramSessionWithSessionRow
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.StateData,
		&i.TgCreatedAt,
		&i.TgUpdatedAt,
		&i.SessionIDFull,
		&i.SessionStatus,
		&i.SessionType,
		&i.SessionProjectID,
	)
	return i, err
}

const upsertTelegramSession = `-- name: UpsertTelegramSession :exec
INSERT INTO telegram_sessions (user_id, session_id, state_data, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    session_id = EXCLUDED.session_id,
    state_data = EXCLUDED.state_data,
    updated_at = EXCLUDED.updated_at
`

type UpsertTelegramSessionParams struct {
	UserID    int64            `json:"user_id"`
	SessionID pgtype.UUID      `json:"session_id"`
	StateData []byte           `json:"state_data"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertTelegramSession(ctx context.Context, arg UpsertTelegramSessionParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramSession,
		arg.UserID,
		arg.SessionID,
		arg.StateData,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
